DROP TABLE IF EXISTS new;
DROP TABLE IF EXISTS team_info;
DROP TABLE IF EXISTS game_reports;

CREATE TABLE new(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT UNIQUE NOT NULL,
    content TEXT NOT NULL,
    publish_date DATE NOT NULL,
    origin TEXT NOT NULL
);

CREATE TABLE team_info(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE game_reports(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    home TEXT NOT NULL,
    away TEXT NOT NULL,
    result TEXT NOT NULL,
    date DATETIME NOT NULL,
    content TEXT NOT NULL
);